INSERT INTO location (id, skill_name)
VALUES
(1, 'Ile-de-France'),
(2, 'Nord-Pas-de-Calais'),
(3, 'Champagne-Ardenne'),
(4, 'Picardie'),
(5, 'Haute-Normandie'),
(6, 'Basse-Normandie'),
(7, 'Bourgogne'),
(8, 'Franche-Comté'),
(9, 'Alsace'),
(10, 'Lorraine'),
(11, 'Languedoc-Roussillon'),
(12, 'Provence-Alpes-Côte d Azur'),
(13, 'Rhône-Alpes'),
(14, 'Aquitaine'),
(15, 'Midi-Pyrénées'),
(16, 'Poitou-Charentes'),
(17, 'Centre'),
(18, 'Bretagne'),
(19, 'Pays de la Loire'),
(20, 'Limousin'),
(21, 'Auvergne').
